// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PhotoViewer")]
[assembly: AssemblyProductAttribute("ActorModelAkka")]
[assembly: AssemblyDescriptionAttribute("Actor Model in F# and Akka.Net")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
